# Generated by Django 4.2.4 on 2023-09-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=20, null=True)),
                ('contact', models.CharField(max_length=20, null=True)),
                ('feedback', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
