# Generated by Django 4.2.4 on 2023-10-02 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gas', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=20, null=True)),
                ('contact', models.CharField(max_length=30, null=True)),
                ('complain', models.CharField(max_length=90, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=20, null=True)),
                ('contact', models.CharField(max_length=30, null=True)),
                ('price', models.CharField(max_length=30, null=True)),
                ('mode', models.CharField(max_length=30, null=True)),
                ('status', models.CharField(max_length=70, null=True)),
                ('paymentdate', models.CharField(max_length=30, null=True)),
                ('gastype', models.CharField(max_length=30, null=True)),
                ('day', models.CharField(max_length=30, null=True)),
                ('invoiceid', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('gender', models.CharField(max_length=10, null=True)),
                ('dob', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booking_date',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='fullname',
            new_name='gastype',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='type',
            new_name='idno',
        ),
        migrations.AddField(
            model_name='booking',
            name='idtype',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='month',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
