# Generated by Django 4.2.4 on 2023-10-03 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gas', '0003_complain_payment_signup_delete_feedback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=20, null=True)),
                ('contact', models.CharField(max_length=20, null=True)),
                ('feedback', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('aadhar', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Complain',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='day',
            new_name='booking_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='gastype',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='idno',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='idtype',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='month',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='name',
        ),
        migrations.AlterField(
            model_name='booking',
            name='address',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
